name: cartalogue
description: A simple product catalog UI built with Flutter
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^7.8.4
  http: ^0.13.6

  # For using icons like CupertinoIcons (iOS-style)
  cupertino_icons: ^1.0.8

  # Optional: for state management if you use Riverpod later
  flutter_riverpod: ^2.5.1

  # Optional: for SVG icons/images if needed
  flutter_svg: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^7.3.1
  build_runner: ^2.4.7
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

  fonts:
    - family: Archivo
      fonts:
        - asset: assets/fonts/Archivo-Regular.ttf
        - asset: assets/fonts/Archivo-SemiBold.ttf

