name: cartalogue
description: A simple product catalog UI built with Flutter
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  auto_route: ^7.8.4
  http: ^0.13.6
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  flutter_svg: ^2.0.7
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^7.3.1
  build_runner: ^2.4.7
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/Placeholder.svg

  fonts:
    - family: Archivo
      fonts:
        - asset: assets/fonts/Archivo-Regular.ttf
        - asset: assets/fonts/Archivo-SemiBold.ttf
